apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  labels:
    app: postfix
spec:
  type: ClusterIP
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
  selector:
    app: postfix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-deployment
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: postfix
        image: cchou0519/postfix-without-auth
        ports:
        - containerPort: 25
        env:
        - name: MYHOSTNAME
          value: "your.dns.com"
        - name: MYNETWORKS
          value: "0.0.0.0/0"
